Game Hub/Models/Games.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Game_Hub.Models
{
    public class Games
    {
        [Key]
        public int id { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Name")]
        public string Game_Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Initial Release")]
        public DateTime Initial_Release { get; set; }

        [Required]
        [StringLength(100)]
        public string Designer { get; set; }

        [Required]
        [StringLength(100)]
        public string Developer { get; set; }

        [Required]
        [StringLength(100)]
        public string Company { get; set; }

        [Required]
        [StringLength(100)]
        public string Genre { get; set; }

        //One to many relationship
        public ICollection<Company> Companies { get; set; }
    }
}

Game Hub/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Game_Hub.Data;
using Game_Hub.Models;

namespace Game_Hub.Controllers
{
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GamesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index(string searchTerm)
        {
            var Games = from s in _context.Games
                        select s;
            if (!string.IsNullOrEmpty(searchTerm))
            {
                Games = Games.Where(s => s.Game_Name.Contains(searchTerm) && s.Company.Contains("Blizzard Entertainment") && s.Genre.Contains("") && s.Designer.Contains(""));// Games with the same Genre/Company will show up
                
            }
            return View(await Games.ToListAsync()); //Display the information in table format 
        }


    

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games
                .FirstOrDefaultAsync(m => m.id == id);
            if (games == null)
            {
                return NotFound();
            }

            return View(games);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Game_Name,Initial_Release,Designer,Developer,Company,Genre")] Games games)
        {
            if (ModelState.IsValid)
            {
                _context.Add(games);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(games);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games.FindAsync(id);
            if (games == null)
            {
                return NotFound();
            }
            return View(games);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Game_Name,Initial_Release,Designer,Developer,Company,Genre")] Games games)
        {
            if (id != games.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(games);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GamesExists(games.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(games);
        }

        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games
                .FirstOrDefaultAsync(m => m.id == id);
            if (games == null)
            {
                return NotFound();
            }

            return View(games);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var games = await _context.Games.FindAsync(id);
            _context.Games.Remove(games);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GamesExists(int id)
        {
            return _context.Games.Any(e => e.id == id);
        }
    }
}

Game Hub/Views/Games/Create.cshtml
@model Game_Hub.Models.Games

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Games</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Game_Name" class="control-label"></label>
                <input asp-for="Game_Name" class="form-control" />
                <span asp-validation-for="Game_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Initial_Release" class="control-label"></label>
                <input asp-for="Initial_Release" class="form-control" />
                <span asp-validation-for="Initial_Release" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Designer" class="control-label"></label>
                <input asp-for="Designer" class="form-control" />
                <span asp-validation-for="Designer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Developer" class="control-label"></label>
                <input asp-for="Developer" class="form-control" />
                <span asp-validation-for="Developer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Game Hub/Views/Games/Delete.cshtml
@model Game_Hub.Models.Games

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Games</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Game_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Game_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Initial_Release)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Initial_Release)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Designer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Designer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Developer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Developer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Game Hub/Views/Games/Details.cshtml
@model Game_Hub.Models.Games

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Games</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Game_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Game_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Initial_Release)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Initial_Release)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Designer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Designer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Developer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Developer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Game Hub/Views/Games/Edit.cshtml
@model Game_Hub.Models.Games

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Games</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Game_Name" class="control-label"></label>
                <input asp-for="Game_Name" class="form-control" />
                <span asp-validation-for="Game_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Initial_Release" class="control-label"></label>
                <input asp-for="Initial_Release" class="form-control" />
                <span asp-validation-for="Initial_Release" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Designer" class="control-label"></label>
                <input asp-for="Designer" class="form-control" />
                <span asp-validation-for="Designer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Developer" class="control-label"></label>
                <input asp-for="Developer" class="form-control" />
                <span asp-validation-for="Developer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Game Hub/Views/Games/Index.cshtml
@model IEnumerable<Game_Hub.Models.Games>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Index";
}

<h1>Games</h1>

@if (SignInManager.IsSignedIn(User))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}


<form asp-controller="Games" asp-action="">
    <p>
        Games <input type="text" name="searchTerm" />
        @*<input type="submit" value="Search"/>*@
        <button type="submit" class="btn btn-primary">Search</button>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Game_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Initial_Release)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Designer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Developer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Count() == 0)
        {
            <tr class="alert-danger">
                <td colspan="8">No Records found</td>
            </tr>
        }

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Game_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Initial_Release)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Designer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Developer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>